Repository npono21/mini-shopify, pull requests merged in 2024-11, with the labels that each got.

#30 Bug: #10 Protect against negative quantities
  src/main/java/SYSC4806Project/Product.java
Labels: bug

#29 Bug: #13 Protect against negative quantities
  src/main/java/SYSC4806Project/ItemQuantityList.java
Labels: bug

#28 #27 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#37 link frontend and backend through controller endpoints.
  src/main/java/SYSC4806Project/Controller.java
  src/main/java/SYSC4806Project/Merchant.java
  src/main/java/SYSC4806Project/MerchantController.java
  src/main/java/SYSC4806Project/Product.java
  src/main/java/SYSC4806Project/Shop.java
  src/main/java/SYSC4806Project/Tag.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/merchant_home.css
  src/main/resources/static/css/merchant_login.css
  src/main/resources/static/css/merchant_register.css
  src/main/resources/static/css/shopper_login.css
  src/main/resources/static/images/Mini-Shopify Logo.png
  src/main/resources/static/images/miguel-sousa-hUBeoOI0TmA-unsplash.jpg
  src/main/resources/static/images/nafinia-putra-Kwdp-0pok-I-unsplash.jpg
  src/main/resources/templates/index.html
  src/main/resources/templates/merchant_home.html
  src/main/resources/templates/merchant_login.html
  src/main/resources/templates/merchant_register.html
  src/main/resources/templates/shopper_login.html
Labels: enhancement

#39 update UML Class diagram
  src/main/java/SYSC4806Project.png
  src/main/java/SYSC4806Project.uml
Labels: documentation

#43 Remove duplicated subclass
  src/main/java/SYSC4806Project/ItemQuantityList.java
  src/main/java/SYSC4806Project/ItemQuantityPair.java
  src/test/java/SYSC4806Project/CartTest.java
  src/test/java/SYSC4806Project/ItemQuantityListTest.java
Labels: bug

#56 Feature/cart And test fixes
  src/main/java/SYSC4806Project/AccessingDataJpaApplication.java
  src/main/java/SYSC4806Project/Buyer.java
  src/main/java/SYSC4806Project/BuyerRepository.java
  src/main/java/SYSC4806Project/Cart.java
  src/main/java/SYSC4806Project/CartController.java
  src/main/java/SYSC4806Project/CartRepository.java
  src/main/java/SYSC4806Project/ItemQuantityList.java
  src/main/java/SYSC4806Project/ItemQuantityListRepository.java
  src/main/java/SYSC4806Project/ItemQuantityPair.java
  src/main/java/SYSC4806Project/ItemQuantityPairRepository.java
  src/main/java/SYSC4806Project/Product.java
  src/main/java/SYSC4806Project/Shop.java
  src/main/java/SYSC4806Project/testRepos/CartTestRepository.java
  src/main/java/SYSC4806Project/testRepos/ItemQuantityListTestRepository.java
  src/main/java/SYSC4806Project/testRepos/ItemQuantityPairTestRepository.java
  src/main/resources/static/css/cart_home.css
  src/main/resources/static/images/eiliv-aceron-_8bnn1GqX70-unsplash.jpg
  src/main/resources/static/images/jakub-kapusnak-Hj53USePB1E-unsplash.jpg
  src/main/resources/templates/cart_home.html
  src/test/java/SYSC4806Project/BuyerTest.java
  src/test/java/SYSC4806Project/CartTest.java
  src/test/java/SYSC4806Project/ItemQuantityListTest.java
  src/test/java/SYSC4806Project/MerchantTest.java
  src/test/java/SYSC4806Project/ShopTest.java
  src/test/java/SYSC4806Project/UserTest.java
Labels: enhancement

#76 Feature/milestone 2 docs and diagrams
  img/milestone-01/SYSC4806Project.png
  img/milestone-01/SYSC4806Project.uml
  img/milestone-01/db-schema-m01.png
  img/milestone-02/m02-db-schema.png
  img/milestone-02/m02-uml-class-diagram.png
  readme.md
Labels: documentation
