Repository npono21/mini-shopify, pull requests merged in 2024-12, with the labels that each got.

#93 move common html to one file
  src/main/resources/templates/buyer_home.html
  src/main/resources/templates/cart_home.html
  src/main/resources/templates/fragments/common.html
  src/main/resources/templates/merchant_home.html
  src/main/resources/templates/merchant_shop.html
  src/main/resources/templates/search_results.html
  src/main/resources/templates/shop_home.html
Labels: refactor

#88 added checkout
  src/main/java/sysc4806/group7/mini_shopify/BuyerController.java
  src/main/java/sysc4806/group7/mini_shopify/Cart.java
  src/main/java/sysc4806/group7/mini_shopify/CartController.java
  src/main/java/sysc4806/group7/mini_shopify/ItemQuantityList.java
  src/main/java/sysc4806/group7/mini_shopify/MerchantController.java
  src/main/java/sysc4806/group7/mini_shopify/Product.java
  src/main/resources/templates/cart_home.html
  src/main/resources/templates/shop_home.html
  src/test/java/sysc4806/group7/mini_shopify/CartControllerTest.java
  src/test/java/sysc4806/group7/mini_shopify/CartTest.java
  src/test/java/sysc4806/group7/mini_shopify/MerchantTest.java
  src/test/java/sysc4806/group7/mini_shopify/ProductTest.java
  src/test/java/sysc4806/group7/mini_shopify/ShopTest.java
Labels: enhancement

#97 Feature/milestone 3 docs and diagrams
  img/milestone-03/m03-db-schema.png
  img/milestone-03/m03-uml-class-diagram.png
  img/milestone-03/m03-uml-class-diagram.uml
  readme.md
Labels: documentation

#98 Feature/add pictures to products
  src/main/java/sysc4806/group7/mini_shopify/BuyerController.java
  src/main/java/sysc4806/group7/mini_shopify/MerchantController.java
  src/main/java/sysc4806/group7/mini_shopify/Product.java
  src/main/java/sysc4806/group7/mini_shopify/ProductController.java
  src/main/java/sysc4806/group7/mini_shopify/ProductRepository.java
  src/main/resources/templates/cart_home.html
  src/main/resources/templates/merchant_shop.html
  src/main/resources/templates/shop_home.html
Labels: enhancement
